name: Trigger auto deployment for ab-testing-tool-aca

on:
  push:
    branches:
      [ main ]
    paths:
    - '**'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ABTESTINGTOOLACA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ABTESTINGTOOLACA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ABTESTINGTOOLACA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: 'Dockerfile'
          registryUrl: akheraabtestingacr.azurecr.io
          registryUsername: ${{ secrets.ABTESTINGTOOLACA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ABTESTINGTOOLACA_REGISTRY_PASSWORD }}
          containerAppName: ab-testing-tool-aca
          resourceGroup: ab-testing-tool-rg
          imageToBuild: akheraabtestingacr.azurecr.io/ab-testing-tool-aca:${{ github.sha }}
          ingress: 'external'
          targetPort: 8080
