name: Trigger auto deployment for ab-testing-tool-aca

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ab-testing-tool-aca-AutoDeployTrigger-424a9eb3-942c-4864-890b-4742196872ed.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ABTESTINGTOOLACA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ABTESTINGTOOLACA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ABTESTINGTOOLACA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: akheraabtestingacr.azurecr.io
          registryUsername: ${{ secrets.ABTESTINGTOOLACA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ABTESTINGTOOLACA_REGISTRY_PASSWORD }}
          containerAppName: ab-testing-tool-aca
          resourceGroup: ab-testing-tool-rg
          imageToBuild: akheraabtestingacr.azurecr.io/ab-testing-tool-aca:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


